name: Python Build Process

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:    

  ci:
    uses: yadickson/workflows/.github/workflows/integration.yml@v1
    with:
      container-image: python:3.12-slim
    secrets: inherit

